version: '3'

services:

  redis:
    image: redis:7.0.0
    hostname: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG", "||", "exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  rabbitmq:
    image: rabbitmq:3.10-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2022-05-19T18-20-59Z
    hostname: minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER} # Minimum 3 chars
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} # Minimum 8 chars

  elasticsearch-base:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    hostname: elasticsearch
    environment:
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms${ELASTICSEARCH_MEMORY_SIZE} -Xmx${ELASTICSEARCH_MEMORY_SIZE}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 3

  elasticsearch-single-node:
    extends: elasticsearch-base
    environment:
      - discovery.type=single-node

  elasticsearch-cluster-node:
    extends: elasticsearch-base
    environment:
      - cluster.name=opencti

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    hostname: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 3